fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: 'tarikzahraoui@gmail.com'
        sender_name: "Kimai 2"
    service:
        mailer: fos_user.mailer.twig_swift    
    registration:
        confirmation:
            enabled: true
            template: Registration_confirming.email.twig
    resetting:
        retry_ttl: 7200
        token_ttl: 86400
        email:
            template: password_resetting.email.twig
    #group:
       # group_class:    ~ # Required when using groups
       # group_manager:  fos_user.group_manager.default
       # form:
            #type:               FOS\UserBundle\Form\Type\GroupFormType # or 'fos_user_group' on Symfony < 2.8
            #name:               fos_user_group_form
            #validation_groups:  [Registration, Default]
