hwi_oauth:
    # Define which firewalls will be used for oauth
    # Usually, its only the main, but you can add it if you have a custom one
    firewall_names: ["main"]
    fosub:
        username_iterations: 30
        # Define in which columns of the fos_user table will be stored
        # the access token of every resource_owner
        properties:
            github: github_id
            facebook: facebook_id
            googleplus: googleplus_id
            stackexchange: stackexchange_id
    # Define the resource_owners that your user can use to login into your app
    # Note that the client_id and client_secret and key values are symfony parameters
    # stored too in the config.yml from the previous step !
    resource_owners:
       # github:
           # type:           github
            #client_id:      "%github_client_id%"
            #client_secret:  "%github_secret%"
            #scope: 'user:email,public_repo'
        facebook:
            type:           facebook
            client_id:      "%facebook_client_id%"
            client_secret:  "%facebook_secret%"
            infos_url:     "https://graph.facebook.com/me?fields=id,name,email"
            scope:               "email"
            options:
                display: popup
                csrf: true

        #googleplus:
         #   type:           google
          ##  client_id:      "%googleplus_client_id%"
            #client_secret:  "%googleplus_secret%"
            #scope:  "email profile"
       # stackexchange:
        #    type:           stack_exchange
         #   client_id:      "%stackexchange_client_id%"
          #  client_secret:  "%stackexchange_secret%"
           # options:
            #    key: "%stackexchange_key%"