# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::index' }

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
    
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

#    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"

#    prefix:   /connect


#hwi_oauth_connect:
 
#   resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
 
#   prefix:   /connect


#hwi_oauth_login:
 
#   resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
 
#   prefix:   /login    
facebook_login:
    path: /login/check-facebook

#google_login:
 #   path: /login/check-google

#custom_login:
 #   path: /login/check-custom

#github_login:
 #   path: /login/check-github